name: CI Pipeline

on:
  push:
    branches:
      - sesi31-loadtest
  pull_request:

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Unit Test with Coverage
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=rafsanjani21_tugas-project-digital-skola-devops
            -Dsonar.organization=rafsanjani21
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
